# §11	异常、日志、断言&调测

## 11.1	处理异常

异常产生原因：输入错误；硬件设备错误；内存等物理限制；代码错误

对方法中出现的异常错误的传统解决方案是返回一个特定的错误编码如-1或者返回null引用，其弊端就是在返回值为整型是无法有效区分返回-1时方法是否真的出现异常。在Java中，如果某个方法不能完整的实现功能，那就通过另一种途径退出方法。对于异常，方法会抛出(throw)一个封装异常信息的对象，此时方法不返回任何值而会立即退出。Java的异常处理机制就会搜索处理这种异常的异常处理器(exception handler)。

## 11.1.1	异常分类

Java中的异常对象都是派生于Throwable类的实例。

下图为异常结构图

Throwable类有两个子类，Error和Exception

> Error类表示Java运行时系统内部的错误或者资源耗尽错误。应用程序不应该抛出这种类型的对象。如果出现了这样的内部错误，尽量及时通知用户，确保程序安全退出。

Exception类又分为RuntimeException和IOException。划分规则是由程序错误导致的异常为RuntimeException，程序本身没有问题，但由于像I/O这种错误导致的异常属于其他异常。

常见的RuntimeException有错误的类型转化，数组下标越界，访问空指针

常见的其他异常有试图在文件尾部后面读取文件，试图打开一个错误格式的url，试图根据给定的字符串找到Class对象，而这个字符串表示的类并不存在。

简单来说，出现RuntimeException说明coder并没有采取措施避免，如判断对象是否为null来避免空指针。对于其他异常如URL错误仅代码是不能避免的，如不同浏览器会处理不同格式的url。

非受检异常(unchecked)/受检异常(checked)异常：所有Error类或者RuntimeException类的子类都是非受检异常，其他的所有异常都是受检异常。

受检异常:

定义方法时必须声明所有可能会抛出的受检异常，在调用这个方法的时候必须用try-catch捕获这个checked exception，或者继续抛出exception，简单来说就是谁调用谁处理。这类异常如果没有try和catch,也没有throws的情况下，编译是不能通过的。必须接受检查。

非受检异常：

在定义方法时不需要声明会抛出runtime exception：在调用这个方法时不需要捕获这个runtime exception；非受检异常是从java.lang.RuntimeException或java.lang.Error类衍生出来的。例如：NullPointException，ArithmeticException（算术异常，除0），IndexOutOfBoundsException，ClassCastException就属于runtime exception。是因为程序员没有进行必需要的检查，因为疏忽和错误而引起的错误。java编译器未检查的代码块，当程序运行时可能出现的异常，在没有try和catch,也没有throws的情况下，仍然可以编译通过

声明受检异常

在Java方法无法返回结果的时候，需要在方法首部声明所有可能出现的异常。这样可以从方法首部就能判断会抛出那些类型的异常。下面是需要抛出异常的集中情况：调用一个抛出受检异常的方法；程序运行过程中发现错误，并用throw抛出一个受检异常;程序出现非受检异常;程序内部错误。

被其他对象调用的方法需要在方法上声明可能抛出的异常，对程序中可能出现的异常，必须在方法首部全部列出。而对于出Error类的非受检异常，如ArrayIndexOutOfBoundsException，在程序中应该通过代码规避；Error类异常每个程序都可能产生，也没有声明的必要。

对于子类重写父类的方法，如果父类的方法抛出异常，那么子类重写的这个方法抛出的异常范围要比父类小或者不抛出异常。如果父类不抛出异常，子类也不能抛出异常。

抛出的异常可以是方法声明可能抛出的异常类对象，也可以是它的的子类对象

如何抛出异常：

将方法中可能的错误找到一个合适的异常类，然后创建这个类的一个对象，最后将这个对象抛出throw

## 11.2	捕获受检异常

通过try-catch块对异常进行捕获，如果在try块中出现了catch块中声明的异常类，那么程序就会立即执行catch块中的代码，不再执行try块中的代码，如果出现了catch块中未声明的异常类，那么方法就会立即退出，如果没有出现catch块中声明的异常类，那么就会跳过catch块的代码。对于是抛出异常还是处理异常的问题，如果在此方法内可以合适的处理异常，那么就处理，否则将它抛出直到合适的调用者来处理。

再次抛出异常和异常链

在catch块中可以抛出一个其他类型的异常对象，目的是为了改变方法抛出的异常类型。这样可以方便定位复杂系统中异常出现的位置而忽略可能的具体异常，如ServletException就是将异常归结为Servlet报错而不关心具体的异常。

捕获异常并再次将其抛出，将原异常信息封装到新异常中

~~~java
try{
code
}catch(SQLException e){
Throwable t = new ServletException();
t.initCause(e);
throw t;
}
~~~

在捕获到异常的时候可以通过se.getCause();获取原始异常信息。

### Finally子句

finally子句一般用来在处理异常后回收本地资源，不管try块中的代码有没有错误，finally块中的代码都会执行

执行规则如下

~~~ java
try{
//1
//2
}catch{
//3
code
//4
}finally{
//5
}
//6

# try块中代码没有异常，执行 1 2 5 6
# 1报错,catch块不报错执行 1 3 4 5 6,catch块3抛出异常执行 1 3 5
# 1报错(非catch捕获的异常),执行 1 5
# 可以看到不管什么情况finally中的代码都会执行
~~~

try...catch和try...finally的嵌套使用

~~~java
try{
	code
	try{
	exception code
	}finally{
	//关闭资源
	}
}catch(IOException e){
//处理异常
}
~~~

这样内层的try...finally只负责关闭资源，外层的try...catch不仅能够处理异常，还能够发现内层finally中的错误

finally块中包含return语句的处理，可以看到try...finally块中都返回结果，先执行try块中的return操作，但是在退出方法之前还会执行finally的代码，所以当执行f(2)方法的时候try块中的返回值会被finally中的覆盖最终会返回0。同时，因为finally块中如果可能抛出异常那么会改变try...catch...finally块的原始异常。

~~~java
public static int f(int n){
    try{
        int r = n;
        return r;
    }finally{
		if(n=2)return 0;
    }
}
~~~

## 带资源的try语句

对于以下代码模式

~~~java
open a resource
try{
	work with the resource
}finally{
	close the resource
}
~~~

假设resources属于一个实现了AutoCloseable接口的类，Java7为这种代码模式提供个很有用的快捷方式。AutoCloseable接口有一个方法：void close() throws Exception

带资源的的try语句(try-with-resources)的最简形式为，这里的资源可以为多个不同的资源

~~~java
try(Resource res = ...)
{
    work with res
}
~~~

try块退出的时候回自动调用res.close()。示例如下

~~~java
try(Scanner sc = new Scanner(new FileInputStream("..."),"UTF-8"))
{
    while(sc.hasNext()){
        print(sc.next())
    }
}
~~~

在try块执行完毕或者存在异常的时候都会调用sc.close()方法，就好像使用了finally来关闭资源一样。

合理使用异常机制

在执行可能发生异常的操作之前，通过判断避免异常；不要过分的细分异常；利用异常层次结构不要只抛出RuntimeException,不要只捕获Throwable异常;早抛出，晚捕获

##断言

> 在程序进行测试的时候会加入很多检查语句，这些语句在测试完毕的时候也不会移走，这些语句一旦增多会影响程序运行速度。断言机制允许程序在测试期间提供一些检查语句，在代码正式发布的时候，这些检查语句将会自动的移走。？

Java语言引入断言机制(1.4)，通过assert关键字，两种形式

assert	条件;

和assert	条件：表达式;

这两种形式都会对条件进行检测，如果返回false则会抛出一个AssertionError异常。在第二种形式中，表达式将被传入AssertionError的构造器，并转换成一个消息字符串。

~~~java
assert x>=0;//断言x是非负数
assert x>=0:x;//把x的值传给AssertionError的构造器
~~~

启用/禁用断言

断言使用场景

##日志

主要用来帮助观察定位程序运行。

日志级别SEVERE,WARNING,INFO,CONFIG,FINE,FINER,FINEST，默认情况下只记录前三个级别。

日志记录尽量与类名/主应用程序包相同

~~~java
private Logger logger = Logger.getLoggger("com.horstman.log");
~~~

为了方便起见，可能希望利用一些日志操作将下面的静态域添加到类中

~~~java
private static final Logger log = Logger.getLogger("com.horstman.log");
~~~

